import { User, Customer, Visit, Reward, LoyaltyRule, Barber, ServiceItem } from '@/types';

export const INITIAL_LOYALTY_RULE: LoyaltyRule = {
  id: 'rule-default-1',
  targetVisits: 5,
  rewardTitle: 'Free Signature Haircut',
  rewardDesc: 'Enjoy a complimentary signature haircut with refreshing hot towel finish.',
  shopName: 'DAHAB Grooming Lounge',
  phonePrefix: '+20',
  isActive: true,
  updatedAt: new Date().toISOString(),
};

export const INITIAL_BARBERS: Barber[] = [
  {
    id: 'barber-1',
    name: 'Tarek "The Master" El-Sayed',
    role: 'Head Stylist & Founder',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    specialty: 'Classic Tapers, Scissor Fades & Royal Shaves',
    rating: 4.9,
  },
  {
    id: 'barber-2',
    name: 'Karim Mostafa',
    role: 'Senior Barber',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    specialty: 'Beard Sculpting, Razor Lineups & Skin Fades',
    rating: 4.8,
  },
  {
    id: 'barber-3',
    name: 'Ziad Mansour',
    role: 'Precision Stylist',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    specialty: 'Modern Textured Crops & Hair Spa Treatments',
    rating: 4.9,
  },
  {
    id: 'barber-4',
    name: 'Omar Reda',
    role: 'Master Groomer',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    specialty: 'Hot Towel Rituals & Charcoal Detox',
    rating: 4.7,
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'srv-1',
    name: 'Dahab Signature Haircut',
    category: 'HAIRCUT',
    duration: '40 min',
    price: 350,
    description: 'Precision cut, neck shave, invigorating wash, and styling with premium pomade.',
    popular: true,
  },
  {
    id: 'srv-2',
    name: 'Haircut + Royal Beard Sculpt',
    category: 'PACKAGE',
    duration: '60 min',
    price: 550,
    description: 'Signature haircut combined with hot towel steam beard trim and razor outline.',
    popular: true,
  },
  {
    id: 'srv-3',
    name: 'Royal Beard Sculpt & Hot Towel',
    category: 'BEARD',
    duration: '30 min',
    price: 250,
    description: 'Hot lather steam, straight razor edge lining, organic beard oil treatment.',
    popular: false,
  },
  {
    id: 'srv-4',
    name: 'Dahab VIP Ritual Experience',
    category: 'PACKAGE',
    duration: '80 min',
    price: 850,
    description: 'Haircut, beard sculpt, deep purifying charcoal facial, eye mask, and espresso.',
    popular: true,
  },
  {
    id: 'srv-5',
    name: 'Charcoal Face Detox & Scrub',
    category: 'TREATMENT',
    duration: '25 min',
    price: 220,
    description: 'Exfoliating black mask, steam extraction, and refreshing botanical toner.',
    popular: false,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin',
    phoneNumber: '01000000000',
    fullName: 'Dahab Admin Master',
    email: 'admin@dahabbarbershop.com',
    role: 'ADMIN',
    passwordHash: 'admin123',
    createdAt: '2026-01-01T10:00:00.000Z',
  },
  {
    id: 'user-cust-1',
    phoneNumber: '01012345678',
    fullName: 'Mohamed Mostafa',
    email: 'mohamed@dahab.com',
    role: 'CUSTOMER',
    passwordHash: '123456',
    createdAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'user-cust-2',
    phoneNumber: '01123456789',
    fullName: 'Ahmed Hassan',
    email: 'ahmed@dahab.com',
    role: 'CUSTOMER',
    passwordHash: '123456',
    createdAt: '2026-01-15T10:00:00.000Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    userId: 'user-cust-1',
    fullName: 'Mohamed Mostafa',
    phoneNumber: '01012345678',
    email: 'mohamed@dahab.com',
    memberCode: 'DHB-4821',
    currentCycle: 1,
    currentVisits: 4,
    lifetimeVisits: 9,
    tier: 'GOLD',
    createdAt: '2026-01-10T10:00:00.000Z',
    updatedAt: '2026-02-28T14:30:00.000Z',
  },
  {
    id: 'cust-2',
    userId: 'user-cust-2',
    fullName: 'Ahmed Hassan',
    phoneNumber: '01123456789',
    email: 'ahmed@dahab.com',
    memberCode: 'DHB-9012',
    currentCycle: 2,
    currentVisits: 5,
    lifetimeVisits: 15,
    tier: 'ROYAL VIP',
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-03-01T16:00:00.000Z',
  },
];

export const INITIAL_VISITS: Visit[] = [
  {
    id: 'visit-1',
    customerId: 'cust-1',
    cycleNumber: 1,
    visitIndexInCycle: 4,
    barberName: 'Tarek "The Master" El-Sayed',
    serviceName: 'Dahab Signature Haircut',
    price: 350,
    notes: 'Classic taper with matte pomade styling.',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'visit-2',
    customerId: 'cust-1',
    cycleNumber: 1,
    visitIndexInCycle: 3,
    barberName: 'Karim Mostafa',
    serviceName: 'Haircut + Royal Beard Sculpt',
    price: 550,
    notes: 'Beard trim & razor outline.',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'visit-3',
    customerId: 'cust-1',
    cycleNumber: 1,
    visitIndexInCycle: 2,
    barberName: 'Tarek "The Master" El-Sayed',
    serviceName: 'Dahab Signature Haircut',
    price: 350,
    notes: 'Regular haircut refresh.',
    createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'visit-4',
    customerId: 'cust-1',
    cycleNumber: 1,
    visitIndexInCycle: 1,
    barberName: 'Ziad Mansour',
    serviceName: 'Dahab Signature Haircut',
    price: 350,
    notes: 'Textured crop styling.',
    createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'visit-5',
    customerId: 'cust-2',
    cycleNumber: 2,
    visitIndexInCycle: 5,
    barberName: 'Tarek "The Master" El-Sayed',
    serviceName: 'Dahab VIP Ritual Experience',
    price: 850,
    notes: 'Full VIP treatment & hot towel facial.',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_REWARDS: Reward[] = [
  {
    id: 'rew-1',
    customerId: 'cust-2',
    cycleNumber: 1,
    voucherCode: 'DAHAB-FREE-8821',
    title: 'Free Signature Haircut',
    description: 'Complimentary signature haircut with hot towel ritual finish.',
    status: 'AVAILABLE',
    earnedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rew-2',
    customerId: 'cust-1',
    cycleNumber: 1,
    voucherCode: 'DAHAB-REDEEMED-1092',
    title: 'Free Signature Haircut',
    description: 'Complimentary signature haircut (Cycle 1 Reward).',
    status: 'REDEEMED',
    earnedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    redeemedAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
